import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const PAYPOL_PLATFORM_WALLET = "0x33F7E5da060A7FEE31AB4C7a5B27F4cC3B020793";

const agents = [
  // ══════════════════════════════════════
  // NATIVE PAYPOL AGENTS (Claude-powered)
  // ══════════════════════════════════════
  {
    name: "Certi-Audit Pro",
    description: "Enterprise-grade smart contract security auditor powered by Claude AI. Detects reentrancy, overflow, access control vulnerabilities, and 50+ known exploit patterns. Returns detailed JSON audit reports with severity ratings.",
    category: "security",
    skills: JSON.stringify(["audit", "security", "solidity", "reentrancy", "vulnerability", "smart-contract", "exploit", "hack", "web3"]),
    basePrice: 300,
    nativeAgentId: "contract-auditor",
    ownerWallet: PAYPOL_PLATFORM_WALLET,
    avatarEmoji: "🛡️",
    isVerified: true,
    totalJobs: 127,
    successRate: 98.4,
    avgRating: 4.9,
    ratingCount: 89,
    responseTime: 15,
  },
  {
    name: "Omnichain Yield Farmer",
    description: "AI-powered DeFi yield optimization engine. Analyzes liquidity pools, staking opportunities, and farming strategies across multiple chains. Maximizes APY while managing risk exposure.",
    category: "defi",
    skills: JSON.stringify(["yield", "farm", "liquidity", "pool", "stake", "apy", "defi", "swap", "dex", "earn"]),
    basePrice: 75,
    nativeAgentId: "yield-optimizer",
    ownerWallet: PAYPOL_PLATFORM_WALLET,
    avatarEmoji: "🌾",
    isVerified: true,
    totalJobs: 234,
    successRate: 95.7,
    avgRating: 4.7,
    ratingCount: 156,
    responseTime: 20,
  },
  {
    name: "PayPol Payroll Planner",
    description: "Intelligent payroll optimization agent. Plans batch disbursements, analyzes gas costs, generates payment schedules, and recommends optimal timing for multi-employee transactions.",
    category: "payroll",
    skills: JSON.stringify(["payroll", "salary", "batch", "gas", "schedule", "payment", "optimization", "employee"]),
    basePrice: 50,
    nativeAgentId: "payroll-planner",
    ownerWallet: PAYPOL_PLATFORM_WALLET,
    avatarEmoji: "📊",
    isVerified: true,
    totalJobs: 312,
    successRate: 99.1,
    avgRating: 4.8,
    ratingCount: 201,
    responseTime: 10,
  },
  {
    name: "Gas Oracle Predictor",
    description: "Real-time gas price prediction and transaction timing optimizer. Uses historical data patterns and mempool analysis to recommend the cheapest execution windows.",
    category: "analytics",
    skills: JSON.stringify(["gas", "predict", "timing", "mempool", "cost", "analytics", "optimize", "transaction"]),
    basePrice: 25,
    nativeAgentId: "gas-predictor",
    ownerWallet: PAYPOL_PLATFORM_WALLET,
    avatarEmoji: "⛽",
    isVerified: true,
    totalJobs: 589,
    successRate: 97.3,
    avgRating: 4.6,
    ratingCount: 342,
    responseTime: 5,
  },

  // ══════════════════════════════════════
  // NATIVE PAYPOL AGENTS (Expanded - Claude + third-party APIs)
  // ══════════════════════════════════════
  {
    name: "Flash Arbitrage Sniper",
    description: "Scans DEX volumes and token prices across chains to identify arbitrage opportunities using DeFiLlama + CoinGecko data. Analyzes price spreads, gas costs, and MEV risk.",
    category: "defi",
    skills: JSON.stringify(["arbitrage", "flashloan", "mev", "trade", "snipe", "dex", "swap", "profit"]),
    basePrice: 250,
    nativeAgentId: "arbitrage-scanner",
    ownerWallet: PAYPOL_PLATFORM_WALLET,
    avatarEmoji: "⚡",
    isVerified: true,
    totalJobs: 67,
    successRate: 91.0,
    avgRating: 4.5,
    ratingCount: 45,
    responseTime: 8,
  },
  {
    name: "LegalEase Compliance Bot",
    description: "AI-powered crypto regulatory compliance advisor. Analyzes tax obligations, licensing requirements, KYC/AML rules, and regulatory frameworks across jurisdictions.",
    category: "compliance",
    skills: JSON.stringify(["tax", "legal", "compliance", "law", "regulation", "audit", "corporate", "dao", "governance"]),
    basePrice: 150,
    nativeAgentId: "compliance-advisor",
    ownerWallet: PAYPOL_PLATFORM_WALLET,
    avatarEmoji: "⚖️",
    isVerified: true,
    totalJobs: 43,
    successRate: 96.5,
    avgRating: 4.8,
    ratingCount: 31,
    responseTime: 45,
  },
  {
    name: "NFT Forensics Investigator",
    description: "Investigates NFT collections for wash trading, suspicious activity, and provenance analysis using on-chain data from Reservoir API. Returns health scores and forensic reports.",
    category: "security",
    skills: JSON.stringify(["nft", "forensics", "investigate", "stolen", "provenance", "wash-trading", "marketplace", "trace"]),
    basePrice: 200,
    nativeAgentId: "nft-forensics",
    ownerWallet: PAYPOL_PLATFORM_WALLET,
    avatarEmoji: "🔍",
    isVerified: true,
    totalJobs: 28,
    successRate: 89.3,
    avgRating: 4.4,
    ratingCount: 19,
    responseTime: 60,
  },
  {
    name: "Bridge Guardian",
    description: "Analyzes cross-chain bridge protocols for security, fees, and speed using DeFiLlama bridge data. Recommends optimal bridging routes with risk scoring.",
    category: "security",
    skills: JSON.stringify(["bridge", "cross-chain", "multichain", "transfer", "routing", "liquidity", "layer2", "rollup"]),
    basePrice: 180,
    nativeAgentId: "bridge-analyzer",
    ownerWallet: PAYPOL_PLATFORM_WALLET,
    avatarEmoji: "🌉",
    isVerified: true,
    totalJobs: 51,
    successRate: 94.1,
    avgRating: 4.3,
    ratingCount: 34,
    responseTime: 25,
  },
  {
    name: "DAO Governance Advisor",
    description: "Analyzes DAO proposals, voting patterns, and governance health using Snapshot data. Provides voting recommendations, quorum tracking, and governance insights.",
    category: "governance",
    skills: JSON.stringify(["dao", "governance", "voting", "proposal", "token", "treasury", "delegation", "quorum"]),
    basePrice: 120,
    nativeAgentId: "dao-advisor",
    ownerWallet: PAYPOL_PLATFORM_WALLET,
    avatarEmoji: "🏛️",
    isVerified: true,
    totalJobs: 19,
    successRate: 100.0,
    avgRating: 4.7,
    ratingCount: 12,
    responseTime: 35,
  },
  {
    name: "Sentinel Risk Analyzer",
    description: "Comprehensive DeFi portfolio risk analysis using DeFiLlama protocol data, TVL trends, and stablecoin metrics. Scores protocol risk, diversification, and systemic exposure.",
    category: "analytics",
    skills: JSON.stringify(["risk", "portfolio", "liquidation", "monitor", "tvl", "exposure", "alert", "defi", "analytics"]),
    basePrice: 200,
    nativeAgentId: "risk-analyzer",
    ownerWallet: PAYPOL_PLATFORM_WALLET,
    avatarEmoji: "🔔",
    isVerified: true,
    totalJobs: 76,
    successRate: 93.4,
    avgRating: 4.5,
    ratingCount: 52,
    responseTime: 12,
  },

  // ══════════════════════════════════════
  // WAVE 2: PRACTICAL CRYPTO AGENTS
  // ══════════════════════════════════════
  {
    name: "CryptoTax Navigator",
    description: "Comprehensive crypto tax calculation and reporting agent. Analyzes wallet transaction history across chains, classifies events (trades, airdrops, staking rewards, LP gains), calculates cost basis using FIFO/LIFO/HIFO, and generates tax-ready reports compatible with IRS, EU, and APAC jurisdictions.",
    category: "tax",
    skills: JSON.stringify(["tax", "report", "capital-gains", "cost-basis", "fifo", "airdrop", "staking", "income", "irs", "filing"]),
    basePrice: 175,
    nativeAgentId: "tax-navigator",
    ownerWallet: PAYPOL_PLATFORM_WALLET,
    avatarEmoji: "🧾",
    isVerified: true,
    totalJobs: 89,
    successRate: 97.2,
    avgRating: 4.7,
    ratingCount: 62,
    responseTime: 30,
  },
  {
    name: "AlphaBalance Portfolio AI",
    description: "AI portfolio management agent that analyzes your DeFi holdings across protocols and chains. Recommends rebalancing strategies based on risk tolerance, correlation analysis, and market conditions using CoinGecko + DeFiLlama data.",
    category: "analytics",
    skills: JSON.stringify(["portfolio", "rebalance", "allocation", "diversify", "risk", "correlation", "holdings", "performance", "tracking"]),
    basePrice: 120,
    nativeAgentId: "portfolio-rebalancer",
    ownerWallet: PAYPOL_PLATFORM_WALLET,
    avatarEmoji: "📊",
    isVerified: true,
    totalJobs: 156,
    successRate: 94.8,
    avgRating: 4.6,
    ratingCount: 108,
    responseTime: 20,
  },
  {
    name: "LaunchPad Token Deployer",
    description: "End-to-end ERC-20/ERC-721 token deployment assistant. Generates audited Solidity contracts with configurable tokenomics (supply, fees, vesting, burn), deploys to EVM chains, and verifies on block explorers. Includes anti-rug safety checks.",
    category: "deployment",
    skills: JSON.stringify(["deploy", "token", "erc20", "erc721", "launch", "tokenomics", "contract", "mint", "supply", "verify"]),
    basePrice: 350,
    nativeAgentId: "token-deployer",
    ownerWallet: PAYPOL_PLATFORM_WALLET,
    avatarEmoji: "🚀",
    isVerified: true,
    totalJobs: 34,
    successRate: 100.0,
    avgRating: 4.9,
    ratingCount: 28,
    responseTime: 45,
  },
  {
    name: "AirdropScan Tracker",
    description: "Monitors and tracks airdrop eligibility across protocols. Analyzes wallet activity against known and predicted airdrop criteria, identifies farming opportunities, and provides step-by-step qualification guides for upcoming token distributions.",
    category: "defi",
    skills: JSON.stringify(["airdrop", "claim", "eligibility", "farming", "distribution", "snapshot", "qualify", "token-drop", "retroactive"]),
    basePrice: 60,
    nativeAgentId: "airdrop-tracker",
    ownerWallet: PAYPOL_PLATFORM_WALLET,
    avatarEmoji: "🪂",
    isVerified: true,
    totalJobs: 421,
    successRate: 92.4,
    avgRating: 4.4,
    ratingCount: 289,
    responseTime: 15,
  },
  {
    name: "MEV Sentinel Shield",
    description: "Protects transactions from MEV attacks including front-running, sandwich attacks, and JIT liquidity. Analyzes mempool exposure, recommends private transaction channels (Flashbots, MEV Blocker), and simulates transaction ordering risks before execution.",
    category: "security",
    skills: JSON.stringify(["mev", "frontrun", "sandwich", "flashbots", "mempool", "private-tx", "protection", "slippage", "ordering"]),
    basePrice: 90,
    nativeAgentId: "mev-shield",
    ownerWallet: PAYPOL_PLATFORM_WALLET,
    avatarEmoji: "🔰",
    isVerified: true,
    totalJobs: 203,
    successRate: 96.1,
    avgRating: 4.7,
    ratingCount: 145,
    responseTime: 8,
  },
  {
    name: "LiquidityOps Manager",
    description: "Manages concentrated liquidity positions on Uniswap V3/V4, Curve, and other AMMs. Monitors price ranges, recommends repositioning, calculates impermanent loss, and optimizes fee tier selection using real-time on-chain pool analytics.",
    category: "defi",
    skills: JSON.stringify(["liquidity", "amm", "uniswap", "curve", "concentrated", "impermanent-loss", "position", "range", "fee-tier", "lp"]),
    basePrice: 140,
    nativeAgentId: "liquidity-manager",
    ownerWallet: PAYPOL_PLATFORM_WALLET,
    avatarEmoji: "💧",
    isVerified: true,
    totalJobs: 167,
    successRate: 93.4,
    avgRating: 4.5,
    ratingCount: 112,
    responseTime: 18,
  },
  {
    name: "WhaleAlert Intelligence",
    description: "Tracks large wallet movements and whale accumulation/distribution patterns in real-time. Monitors smart money flows, exchange inflows/outflows, and dormant wallet activations. Provides behavioral analysis using on-chain data from Etherscan and Arkham.",
    category: "analytics",
    skills: JSON.stringify(["whale", "tracking", "smart-money", "exchange-flow", "accumulation", "distribution", "large-tx", "wallet-watch", "alert"]),
    basePrice: 80,
    nativeAgentId: "whale-watcher",
    ownerWallet: PAYPOL_PLATFORM_WALLET,
    avatarEmoji: "🐋",
    isVerified: true,
    totalJobs: 312,
    successRate: 95.5,
    avgRating: 4.6,
    ratingCount: 215,
    responseTime: 10,
  },
  {
    name: "SentiChain Social Radar",
    description: "Analyzes crypto social sentiment across Twitter/X, Discord, Telegram, and governance forums. Scores token sentiment from -100 to +100, detects coordinated shilling campaigns, and correlates social signals with price action using advanced NLP.",
    category: "analytics",
    skills: JSON.stringify(["sentiment", "social", "twitter", "discord", "telegram", "nlp", "trending", "hype", "fud", "narrative"]),
    basePrice: 65,
    nativeAgentId: "sentiment-analyzer",
    ownerWallet: PAYPOL_PLATFORM_WALLET,
    avatarEmoji: "📡",
    isVerified: true,
    totalJobs: 245,
    successRate: 91.8,
    avgRating: 4.3,
    ratingCount: 178,
    responseTime: 12,
  },
  {
    name: "OmniBridge Router",
    description: "Finds the cheapest, fastest, and safest bridge route for any cross-chain transfer. Compares fees, speed, liquidity depth, and security ratings across 20+ bridge protocols in real-time using aggregated data from DeFiLlama and Li.Fi.",
    category: "defi",
    skills: JSON.stringify(["bridge", "cross-chain", "route", "transfer", "l2", "rollup", "cheapest", "fastest", "multichain", "interop"]),
    basePrice: 40,
    nativeAgentId: "bridge-optimizer",
    ownerWallet: PAYPOL_PLATFORM_WALLET,
    avatarEmoji: "🔗",
    isVerified: true,
    totalJobs: 534,
    successRate: 97.6,
    avgRating: 4.8,
    ratingCount: 398,
    responseTime: 6,
  },
  {
    name: "NFT Appraisal Engine",
    description: "Estimates fair market value of NFTs using rarity analysis, floor price trends, trait distribution, comparable sales history, and collection health metrics from Reservoir and OpenSea APIs. Returns confidence-scored valuations.",
    category: "nft",
    skills: JSON.stringify(["nft", "valuation", "appraisal", "rarity", "floor-price", "collection", "trait", "opensea", "pricing", "estimate"]),
    basePrice: 100,
    nativeAgentId: "nft-valuator",
    ownerWallet: PAYPOL_PLATFORM_WALLET,
    avatarEmoji: "🎨",
    isVerified: true,
    totalJobs: 98,
    successRate: 88.8,
    avgRating: 4.2,
    ratingCount: 67,
    responseTime: 25,
  },
  {
    name: "ProposalForge Writer",
    description: "Drafts professional DAO governance proposals from natural language descriptions. Structures proposals with motivation, specification, rationale, risk analysis, and implementation timeline. Formats for Snapshot, Tally, or custom governance frameworks.",
    category: "governance",
    skills: JSON.stringify(["proposal", "governance", "dao", "draft", "snapshot", "tally", "voting", "specification", "treasury", "grant"]),
    basePrice: 85,
    nativeAgentId: "proposal-writer",
    ownerWallet: PAYPOL_PLATFORM_WALLET,
    avatarEmoji: "📝",
    isVerified: true,
    totalJobs: 56,
    successRate: 98.2,
    avgRating: 4.8,
    ratingCount: 42,
    responseTime: 40,
  },
  {
    name: "VestingVault Planner",
    description: "Designs and audits token vesting schedules for teams, investors, and advisors. Generates cliff/linear/milestone-based vesting contracts, models unlock impact on circulating supply, and provides tokenomics health scoring with visual unlock calendars.",
    category: "compliance",
    skills: JSON.stringify(["vesting", "unlock", "cliff", "schedule", "tokenomics", "supply", "team", "investor", "lock", "distribution"]),
    basePrice: 130,
    nativeAgentId: "vesting-planner",
    ownerWallet: PAYPOL_PLATFORM_WALLET,
    avatarEmoji: "🔒",
    isVerified: true,
    totalJobs: 41,
    successRate: 100.0,
    avgRating: 4.9,
    ratingCount: 35,
    responseTime: 35,
  },
  {
    name: "InsureGuard DeFi Cover",
    description: "Finds and compares DeFi insurance products across Nexus Mutual, InsurAce, Unslashed, and other providers. Analyzes protocol coverage availability, premium costs, claim history, and recommends optimal coverage for your portfolio exposure.",
    category: "defi",
    skills: JSON.stringify(["insurance", "cover", "nexus-mutual", "premium", "claim", "protection", "hack", "exploit", "risk-transfer", "policy"]),
    basePrice: 70,
    nativeAgentId: "insurance-finder",
    ownerWallet: PAYPOL_PLATFORM_WALLET,
    avatarEmoji: "🏥",
    isVerified: true,
    totalJobs: 73,
    successRate: 95.9,
    avgRating: 4.5,
    ratingCount: 49,
    responseTime: 20,
  },
  {
    name: "ContractDeploy Pro",
    description: "Deploys and verifies pre-audited smart contract templates (multisigs, vaults, token locks, payment splitters, DAOs) to any EVM chain. Handles constructor args, gas estimation, proxy patterns, and automatic Etherscan/Sourcify verification.",
    category: "deployment",
    skills: JSON.stringify(["deploy", "smart-contract", "verify", "multisig", "vault", "proxy", "etherscan", "evm", "foundry", "hardhat"]),
    basePrice: 280,
    nativeAgentId: "contract-deployer",
    ownerWallet: PAYPOL_PLATFORM_WALLET,
    avatarEmoji: "⚙️",
    isVerified: true,
    totalJobs: 22,
    successRate: 100.0,
    avgRating: 4.9,
    ratingCount: 18,
    responseTime: 60,
  },
];

async function main() {
  console.log("🤖 Seeding Agent Marketplace...\n");

  for (const agent of agents) {
    // Upsert by name - allows re-running seed to update existing agents
    const upserted = await prisma.marketplaceAgent.upsert({
      where: { name: agent.name },
      create: agent,
      update: {
        description: agent.description,
        category: agent.category,
        skills: agent.skills,
        basePrice: agent.basePrice,
        nativeAgentId: (agent as any).nativeAgentId ?? null,
        ownerWallet: agent.ownerWallet,
        avatarEmoji: agent.avatarEmoji,
        isVerified: agent.isVerified,
      },
    });
    const badge = agent.isVerified ? "✅ Native" : "🌐 Third-party";
    console.log(`  ${badge}  ${agent.avatarEmoji} ${upserted.name} (${upserted.id})`);
  }

  const count = await prisma.marketplaceAgent.count();
  console.log(`\n✨ Done! ${count} agents registered in marketplace.`);
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
