import { NextResponse } from 'next/server';
import prisma from "@/app/lib/prisma";

export const dynamic = 'force-dynamic';

export async function GET() {
    try {
        // Fetch all completed payloads (processed by Daemon or Public Batch)
        const completedTx = await prisma.timeVaultPayload.findMany({
            where: { status: 'COMPLETED' },
            orderBy: { createdAt: 'desc' }
        });

        // Map data to the format expected by LedgerHistory UI
        const formattedHistory = completedTx.map(tx => ({
            // Use zkProof (where Admin's deposit hash is stored) to group batches. Fallback to ID.
            hash: tx.zkProof || tx.id, 
            date: tx.createdAt.toLocaleString('en-GB'),
            amount: tx.amount || 0,
            token: tx.token,
            name: tx.name || 'Unknown Entity',
            address: tx.recipientWallet,
            note: tx.note,
            isShielded: tx.isShielded,
            // 🌟 THE REAL MAGIC: This is the actual ZK-SNARK execution hash generated by the Daemon!
            zkCommitment: tx.zkCommitment 
        }));

        return NextResponse.json(formattedHistory);
    } catch (error: any) {
        console.error("History fetch error:", error);
        return NextResponse.json({ error: "Failed to fetch history" }, { status: 500 });
    }
}