// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import "@openzeppelin/contracts/token/ERC20/IERC20.sol";
import "@openzeppelin/contracts/token/ERC20/utils/SafeERC20.sol";
import "@openzeppelin/contracts/access/Ownable.sol";

contract PayPolMultisendVault is Ownable {
    using SafeERC20 for IERC20;

    IERC20 public immutable paymentToken;
    address public masterDaemon;

    event BatchDisbursed(uint256 totalRecipients, uint256 totalAmount, bytes32 batchId);
    event DaemonUpdated(address newDaemon);

    constructor(address _paymentToken, address _masterDaemon) Ownable(msg.sender) {
        paymentToken = IERC20(_paymentToken);
        masterDaemon = _masterDaemon;
    }

    modifier onlyDaemon() {
        require(msg.sender == masterDaemon, "PayPol: Only Master Daemon can trigger execution");
        _;
    }

    /**
     * @dev PUSH MECHANISM: Sends funds directly to employees' wallets in one loop.
     * @param recipients Array of employee wallet addresses
     * @param amounts Array of amounts corresponding to each employee
     * @param batchId A unique ID generated by the Backend to track this specific payroll batch
     */
    function executePublicBatch(
        address[] calldata recipients, 
        uint256[] calldata amounts,
        bytes32 batchId
    ) external onlyDaemon {
        require(recipients.length == amounts.length, "PayPol: Array length mismatch");
        require(recipients.length > 0, "PayPol: Empty arrays");

        uint256 totalAmount = 0;

        // Loop 1: Transfer funds to employees
        for (uint256 i = 0; i < recipients.length; i++) {
            require(recipients[i] != address(0), "PayPol: Invalid recipient address");
            require(amounts[i] > 0, "PayPol: Amount must be > 0");
            
            // Execute direct transfer from Vault to Employee
            paymentToken.safeTransfer(recipients[i], amounts[i]);
            
            totalAmount += amounts[i];
        }

        emit BatchDisbursed(recipients.length, totalAmount, batchId);
    }

    // Admin function to update the Daemon bot if needed
    function updateMasterDaemon(address _newDaemon) external onlyOwner {
        masterDaemon = _newDaemon;
        emit DaemonUpdated(_newDaemon);
    }
    
    // Admin function to deposit funds into the vault for payroll
    function depositFunds(uint256 amount) external {
        paymentToken.safeTransferFrom(msg.sender, address(this), amount);
    }
}